spring:
  sql:
    init:
      mode: always
  datasource:
    url: "jdbc:mysql://localhost/shopping_cart"
    username: "root"
    password: "password"
  jpa:
    defer-datasource-initialization: true
    show-sql: true
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.MySQLInnoDBDialect

server:
  port: 5000
  servlet:
    context-path: "/api"
